version: '3.8'
services:
  db:
    image: postgres:16.0
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dashboard_lab
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data #pgdata is local, /var/lib/postgresql/data is in container
      - ./database/backup:/backup/postgres

  admin:
    image: adminer
    # restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    # networks:
    #   - backend

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

volumes:
  rabbitmq_data:
  rabbitmq_logs: